---
branches:
  only:
    - master
language: node_js
node_js:
  - "lts/*"
  - "node"
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g cross-env
  - npm install -g semantic-release
  - npm install -g codeclimate-test-reporter
install:
  - npm i .
script:
  - npm run cover
after_success:
  - npx tsc
  - npm run codeclimate:report
  - npm run semantic-release
